linters-settings:
  gci:
    local-prefixes: github.com/chef/ci-studio-common

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - typecheck
    - unconvert
    - varcheck
    - whitespace
  # disable
    # - dupl
    # - errorlint
    # - exhaustivestruct
    # - gochecknoglobals
    # - gochecknoinits
    # - goconst
    # - gocritic
    # - goerr113
    # - golint
    # - gosec
    # - gosimple
    # - interfacer
    # - lll
    # - maligned
    # - scopelint
    # - staticcheck
    # - stylecheck
    # - testpackage
    # - tparallel
    # - unparam
    # - unused
    # - wrapcheck
    # - wsl

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        # Don't enforce function length in test files (lots of t.Run)
        - funlen
        - dupl