sudo: required

branches:
  only:
    - master

before_install:
  - export PATH="$PATH:$HOME/ci-studio-common/bin:$HOME/tools/bin"
  - ln -sf "$TRAVIS_BUILD_DIR" "$HOME/ci-studio-common"

matrix:
  include:

    # lint
    - env:
        - NAME=lint
      install: install-tool hab aws
      script: hab-verify in-studio ci_lint

    # syntax
    - env:
        - NAME=syntax
      install: install-tool hab aws
      script: hab-verify in-studio ci_syntax

    # habitat-lint
    - env:
        - NAME=habitat-lint
      script: hab-verify lint

    # habitat-syntax
    - env:
        - NAME=habitat-syntax
      script: hab-verify syntax
