sudo: required

branches:
  only:
    - master

before_install:
  - export PATH="$PATH:$HOME/ci-studio-common/bin:$HOME/tools/bin"
  - ln -sf "$TRAVIS_BUILD_DIR" "$HOME/ci-studio-common"

matrix:
  include:

    - env: NAME=bats
      script: bats tests

    - env: NAME=in-studio
      install:
        - install-tool hab
        - install-tool aws
        - aws-configure chef-cd
      script:
        - hab-verify in-studio ci_lint
        - hab-verify in-studio ci_syntax

    - env: NAME=habitat
      script:
        - hab-verify lint
        - hab-verify syntax
