#!/bin/bash
#
# Copyright:: Copyright 2018 Chef Software, Inc.
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Defining a few helper functions that are only available when habitat builds a package
# => https://www.habitat.sh/docs/reference/#plan-helper-functions
#
# This is very useful when we need to re-use scaffolding callbacks
function pkg_path_for() {
  hab pkg path "$1"
}
function build_line() {
  echo -e "  $(blue hab-studio:) $1"
}
# Use `exit_with` only in very critical situations where you need to exit completely from the studio
function exit_with() {
  error "$1"
  exit "$2"
}
