#!/bin/bash
#
# Copyright:: Copyright 2017 Chef Software, Inc.
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

document "enforce_integration_testing" <<DOC
  Print an error message if any of the required Integration Testing functions are missing.
DOC
function enforce_integration_testing() {
  local commands=(start_service stop_service inspec_exec start_dependencies stop_dependencies)

  for command in "${commands[@]}"
  do
    if ! type "$command" &> /dev/null
    then
      error "Your .studiorc file, or a file in the .studio direcotry, must declare the '$command' function."
      error "Please see https://github.com/chef/ci-studio-common#running-integration-tests for more information."
      return 1
    fi
  done
}

document "integration_tests" <<DOC
  Provision, Verify, and Destroy your full Integration Testing environment.
DOC
function integration_tests() {
  start_dependencies
  start_service
  inspec_exec
  stop_service
  stop_dependencies
}

document "start_service" <<DOC
  (MISSING) You must provide a custom start_service() function.

  This function should bring up an instance of your Habitat package as a service.
DOC


document "stop_service" <<DOC
  (MISSING) You must provide a custom stop_service() function.

  This function should bring down the instance of your Habitat package as a service.
DOC

document "start_dependencies" <<DOC
  (MISSING) You must provide a custom start_dependencies() function.

  This function should bring up all the dependent services your service requires to function.
DOC

document "stop_dependencies" <<DOC
  (MISSING) You must provide a custom stop_dependencies() function.

  This function should bring down all the dependent services your service requires to function.
DOC

document "inspec_exec" <<DOC
  (MISSING) You must provide a custom inspec_exec() function.

  This function should execute the necessary inspec tests against your acceptance environment.
DOC
