#!/bin/bash
#
# Copyright:: Copyright 2017 Chef Software, Inc.
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

document "ipaddress" <<DOC
  Returns the IPv4 address of the studio.
DOC
function ipaddress() {
  if [[ "${IPADDRESS}" == "" ]]; then
    install_if_missing core/busybox-static ifconfig
    ip_address=$(ifconfig eth0 | grep inet | awk '{print $2}' | cut -f2 -d:)
    export IPADDRESS="$ip_address"
  fi
  echo "$IPADDRESS"
}

document "configure_host" <<DOC
  Configure a host (in /etc/hosts) inside the studio.

  This function will modify the /etc/hosts with @(arg:1) as the hostname and it will
  use @(arg:2) to find the ipaddress that the port is bound to.

  Only if the provided host is NOT an ipaddress

  @(arg:1) The hostname to configure
  @(arg:2) The port used to identify which IP Address to associate with the hostname
DOC
function configure_host() {
  # Return if the hostname to configure ($1) is an ipaddress
  if [[ -z $(tr -d "[:digit:].:" <<< "$1") ]]; then
    return 1
  fi

  # Verify if we have already added the host to /etc/hosts
  if grep -w "$1" /etc/hosts >/dev/null; then
    return 0
  fi

  # Find the ipaddress that the port is bound to
  install_if_missing core/busybox-static netstat
  BIND_ADDRESS=$(netstat -an | grep "$2" | grep LISTEN | awk '{ print $4 }')
  if [[ "$BIND_ADDRESS" == "" ]]; then
    LOCALHOST=$(head -1 /etc/hosts)
    LOCALHOST="$LOCALHOST $HOST"
    ETC=$(awk 'NR==1 {$0="'"$LOCALHOST"'"} 1' /etc/hosts)
    echo "$ETC" > /etc/hosts
  else
    echo -e "\\n$(echo "$BIND_ADDRESS" | cut -f1 -d:) $1" >> /etc/hosts
  fi

  echo "hosts: files dns" > /etc/nsswitch.conf
}
