#!/bin/bash
#
# Copyright:: Copyright 2017 Chef Software, Inc.
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

document "wait_for_success" <<DOC
  Wait for the given command to succeed.

  @(arg:*) The command to run

  Example 1
  ---------
  wait_for_success curl localhost:8080/status
DOC
function wait_for_success() {
  while : ; do
    if eval "$@" >/dev/null 2>/dev/null
    then
      break
    else
      sleep 1
    fi
    echo " => Waiting for '$*' to succeed."
  done
}

document "wait_for_svc_to_load" <<DOC
  Helper function to wait for a Habitat service (hab svc) to be loaded by the Habitat Supervisor.

  @(arg:1) PKG_IDENT A Habitat package identifier (ex: core/redis)
  @(arg:2) Wheter or not this process runs silently
DOC
function wait_for_svc_to_load() {
  while [[ $(hab sup status "$1" | awk -F, '{gsub(/ /, "", $2); print $2}') != "state:up" ]]; do
    sleep 1
    [[ "$2" != "silent" ]] && echo " => Waiting to load svc $1"
  done
}

document "wait_for_port_to_listen" <<DOC
  Wait for a port to be listening.

  @(arg:1) Port to wait for to be listening
  @(arg:2) Wheter or not this process runs silently
DOC
function wait_for_port_to_listen() {
  install_if_missing core/busybox-static netstat
  echo " => deprecated use wait_or_fail_for_port_to_listen"

  while : ; do
    if netstat -an | grep "$1" | grep LISTEN >/dev/null 2>/dev/null
    then
      break
    else
      sleep 1
    fi
    [[ "$2" != "silent" ]] && echo " => Waiting for port $1 to be listening"
  done
}

document "wait_or_fail_for_port_to_listen" <<DOC
  Wait for a port to be listening. If the port is not found in the set amount of time the function exits with 1
  
  @(arg:1) Port to wait for to be listening
  @(arg:2) Number of seconds to wait to exit with 1. Default 60 seconds.
  @(arg:3) Wheter or not this process runs silently

  Example: Wait for a service to start listening on port 1234 for 1 minute
  ---------------------------------------------
  wait_or_fail_for_port_to_listen 1234 60

  Example: Wait for a service to start listening on port 1234 for 10 seconds
  ---------------------------------------------
  wait_or_fail_for_port_to_listen 1234 10
DOC
function wait_or_fail_for_port_to_listen() {
  install_if_missing core/busybox-static netstat
  local SECONDS_WAITING=${2:-60}
  
  local COUNTER=0
  while : ; do
    if netstat -an | grep "$1" | grep LISTEN >/dev/null 2>/dev/null
    then
      break
    else
      sleep 1
    fi

    if [ $COUNTER -ge $SECONDS_WAITING ]
    then
      echo " => Failed listening for port $1"
      exit 1
    fi
    let COUNTER=COUNTER+1
    [[ "$3" != "silent" ]] && echo " => Waiting for port $1 to be listening ($COUNTER of $SECONDS_WAITING)"
  done
}

document "wait_for_ok_response" <<DOC
  Wait a set amount of time for the provided URL to response with status code (200). 
  If the time expires then exit with 1

  @(arg:1) URL to curl
  @(arg:2) Number of seconds to wait to exit with 1. Default 60 seconds

  Example: Wait for www.google.com to return Ok for 1 minute
  ---------------------------------------------
  wait_or_fail_for_ok_response www.google.com 60

  Example: Wait for www.google.com to return Ok for 10 seconds
  ---------------------------------------------
  wait_or_fail_for_ok_response www.google.com 10
DOC
function wait_for_ok_response() {
  [[ "$1" == "" ]] && echo "Missing url argument; try 'describe wait_for_ok_response'" && return 1;

  local SECONDS_WAITING=${2:-60}

  code=200;
  install_if_missing core/curl curl
  local COUNTER=0
  while : ; do
    if [ $COUNTER -ge $SECONDS_WAITING ]
    then
      echo " => Failed listening for port $1"
      exit 1
    fi
    let COUNTER=COUNTER+1

    local response=$(curl --write-out %{http_code} --silent --output /dev/null $1)
    [[ $response -eq $code ]] && break || sleep 1
    echo " => Waiting for '$1' to response OK ($code). [Got:$response] ($COUNTER of $SECONDS_WAITING)"
  done
}
