#!/bin/bash
#
# Copyright:: Copyright 2017 Chef Software, Inc.
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

document "wait_for_success" <<DOC
  Wait for the given command to succeed.

  @(arg:*) The command to run

  Example 1
  ---------
  wait_for_success curl localhost:8080/status
DOC
function wait_for_success() {
  while : ; do
    if eval "$@" >/dev/null 2>/dev/null
    then
      break
    else
      sleep 1
    fi
    echo " => Waiting for $1 to come online"
  done
}

document "wait_for_svc_to_load" <<DOC
  Helper function to wait for a Habitat service (hab svc) to be loaded by the Habitat Supervisor.

  @(arg:1) PKG_IDENT A Habitat package identifier (ex: core/redis)
  @(arg:2) Wheter or not this process runs silently
DOC
function wait_for_svc_to_load() {
  while [[ $(hab sup status "$1" | awk -F, '{gsub(/ /, "", $2); print $2}') != "state:up" ]]; do
    sleep 1
    [[ "$2" != "silent" ]] && echo " => Waiting to load svc $1"
  done
}

document "wait_for_port_to_listen" <<DOC
  Wait for a port to be listening.

  @(arg:1) Port to wait for to be listening
  @(arg:2) Wheter or not this process runs silently
DOC
function wait_for_port_to_listen() {
  while : ; do
    if netstat -an | grep "$1" | grep LISTEN >/dev/null 2>/dev/null
    then
      break
    else
      sleep 1
    fi
    [[ "$2" != "silent" ]] && echo " => Waiting for port $1 to be listening"
  done
}
