#!/bin/bash
#
# This is named 'z_core' so it is always the last library to load.
#
# Copyright:: Copyright 2017 Chef Software, Inc.
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Install and binlink the pkg_deps for ci-studio-common
ci_studio_common_helpers=($(cat "$(hab pkg path "chef/ci-studio-common")/DEPS"))
install "${ci_studio_common_helpers[@]}"

echo "Common helpers from ci-studio-common have been added. Run 'describe' for more information."
