project:
  alias: ci-studio-common

slack:
  notify_channel:
    - releng-notify
    - ci-studio-discuss

pipelines:
  - verify:
      public: true
  - habitat/build

github:
  delete_branch_on_merge: true
  release_branch:
    - master:
        version_constraint: 2.*
    - 1-stable:
        version_constraint: 1.*
    - pre-1.0:
        version_constraint: 0.*

promote:
  channels:
    - dev
    - stable
  actions:
    - built_in:promote_habitat_packages

merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Expeditor: Skip Version Bump"
        - "Expeditor: Skip All"
  - built_in:update_changelog:
      ignore_labels:
        - "Expeditor: Skip Changelog"
        - "Expeditor: Skip All"
  - bash:.expeditor/update_readme.sh:
      ignore_labels:
        - "Expeditor: Skip All"
  # Do not build at the moment -- still working that out
  # - bash:.expeditor/build.sh:
  #     post_commit: true
  #     ignore_labels:
  #       - "Expeditor: Skip All"
  # - trigger_pipeline:habitat/build:
  #     only_if_modified:
  #       - studio-common/*
  #     ignore_labels:
  #       - "Expeditor: Skip Habitat"
  #       - "Expeditor: Skip All"

subscriptions:
  - workload: artifact_published:stable:habitat:*
    actions:
      - bash:.expeditor/update_hab_version.sh
