project:
  alias: ci-studio-common-1

slack:
  notify_channel:
    - releng-notify
    - ci-studio-discuss

pipelines:
  - habitat/build
  - habitat/build-canary:
      canary: true
      definition: .expeditor/build.habitat.yml

github:
  delete_branch_on_merge: true
  release_branch:
    - master:
        version_constraint: 2.*
    - 1-stable:
        version_constraint: 1.*
    - pre-1.0:
        version_constraint: 0.*

promote:
  channels:
    - dev
    - stable
  actions:
    - built_in:promote_habitat_packages

subscriptions:
  - workload: pull_request_merged:{{agent_id}}:*
    actions:
      - built_in:bump_version:
          ignore_labels:
            - "Expeditor: Skip Version Bump"
            - "Expeditor: Skip All"
      - built_in:update_changelog:
          ignore_labels:
            - "Expeditor: Skip Changelog"
            - "Expeditor: Skip All"
      - bash:.expeditor/update_readme.sh:
          ignore_labels:
            - "Expeditor: Skip All"
          only_if_modified:
            - README.md
            - bin/*
      - trigger_pipeline:habitat/build:
          ignore_labels:
            - "Expeditor: Skip Habitat"
            - "Expeditor: Skip All"
  - workload: buildkite_build_passed:chef/core-buildkite-pipelines:master:deploy/chef-canary:*
    actions:
      - trigger_pipeline:habitat/build-canary
  - workload: buildkite_build_passed:chef/core-buildkite-pipelines:master:deploy/chef:*
    actions:
      - trigger_pipeline:habitat/build
  - workload: buildkite_build_passed:chef/habitat-buildkite-pipelines:master:deploy/chef-canary:*
    actions:
      - trigger_pipeline:habitat/build-canary
  - workload: buildkite_build_passed:chef/habitat-buildkite-pipelines:master:deploy/chef:*
    actions:
      - trigger_pipeline:habitat/build
