slack:
  notify_channel:
    - releng-notify
    - ci-studio-discuss

habitat_packages:
  - ci-studio-common

github:
  delete_branch_on_merge: true

promote:
  channels:
    - dev
    - stable

merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Version: Skip Bump"
        - "Expeditor: Skip All"
  - built_in:update_changelog:
      ignore_labels:
        - "Changelog: Skip Update"
        - "Expeditor: Skip All"
  - bash:.expeditor/update_docker-compose_version.sh:
      ignore_labels:
        - "Expeditor: Skip All"
      only_if_modified:
        - tools/docker-compose/VERSION
  - bash:.expeditor/update_hab_version.sh:
      ignore_labels:
        - "Expeditor: Skip All"
      only_if_modified:
        - tools/hab/VERSION
  - bash:.expeditor/update_terraform_version.sh:
      ignore_labels:
        - "Expeditor: Skip All"
      only_if_modified:
        - tools/terraform/VERSION
  - bash:.expeditor/update_readme.sh:
      ignore_labels:
        - "Expeditor: Skip All"
      only_if_modified:
        - README.md
        - bin/*
  - built_in:trigger_habitat_package_build:
      ignore_labels:
        - "Habitat: Skip Build"
        - "Expeditor: Skip All"
  - bash:.expeditor/promote_hab_pkg.sh:
      post_commit: true
      only_if: built_in:trigger_habitat_package_build
