project:
  alias: ci-studio-common

slack:
  notify_channel:
    - releng-notify
    - ci-studio-discuss

pipelines:
  - habitat/build

github:
  delete_branch_on_merge: true
  release_branch:
    - master:
        version_constraint: 1.*
    - pre-1.0:
        version_constraint: 0.*

promote:
  channels:
    - dev
    - stable
  actions:
    - built_in:promote_habitat_packages

merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Expeditor: Skip Version Bump"
        - "Expeditor: Skip All"
  - built_in:update_changelog:
      ignore_labels:
        - "Expeditor: Skip Changelog"
        - "Expeditor: Skip All"
  - bash:.expeditor/update_readme.sh:
      ignore_labels:
        - "Expeditor: Skip All"
      only_if_modified:
        - README.md
        - bin/*
  - trigger_pipeline:habitat/build:
      ignore_labels:
        - "Expeditor: Skip Habitat"
        - "Expeditor: Skip All"

subscriptions:
  - workload: artifact_published:stable:habitat:*
    actions:
      - bash:.expeditor/update_hab_version.sh
