slack:
  notify_channel: eng-services-notify

habitat_packages:
  - ci-studio-common

merge_actions:
  - built_in:trigger_habitat_package_build:
      ignore_labels:
        - "Habitat: Skip Build"
        - "Expeditor: Skip All"
