slack:
  notify_channel:
    - releng-notify
    - ci-studio-discuss

habitat_packages:
  - ci-studio-common

github:
  delete_branch_on_merge: true
  release_branch:
    - master:
        version_constraint: 1.*
    - pre-1.0:
        version_constraint: 0.*

promote:
  channels:
    - dev
    - stable
  actions:
    - built_in:promote_habitat_packages

merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Version: Skip Bump"
        - "Expeditor: Skip All"
  - built_in:update_changelog:
      ignore_labels:
        - "Changelog: Skip Update"
        - "Expeditor: Skip All"
  - bash:.expeditor/update_readme.sh:
      ignore_labels:
        - "Expeditor: Skip All"
      only_if_modified:
        - README.md
        - bin/*
  - built_in:trigger_habitat_package_build:
      ignore_labels:
        - "Habitat: Skip Build"
        - "Expeditor: Skip All"

subscriptions:
  - workload: artifact_published:stable:habitat:*
    actions:
      - bash:.expeditor/update_hab_version.sh
